---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-etcd-snapshot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
    limits:
      storage: 100G
  storageClassName: etcd-snapshot
...
