apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: etcd-snapshot
provisioner: nfs.csi.k8s.io
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: false
volumeBindingMode: Immediate

