---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 88-master-etcd-snapshot
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - path: /usr/local/bin/etcd-snapshot.sh
        contents:
          source: >-
            data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKClNOQVBTSE9UX0hPU1Q9JHsxfQpTTkFQU0hPVF9ESVI9JHsyOi0vaG9tZS9jb3JlL2V0Y2Qtc25hcHNob3RzfQpTTkFQU0hPVF9EQVlTPSR7MzotN30KVEhJU19IT1NUPSQoaG9zdG5hbWUpClZBTElEX0RJUlM9Ii9ob21lL2NvcmUgL21udCAvdG1wIC92YXIiCgplY2hvICItLS0gUnVudGltZSAtLS0iCmVjaG8gIlNOQVBTSE9UX0hPU1Q9JHtTTkFQU0hPVF9IT1NUfSIKZWNobyAiU05BUFNIT1RfRElSPSR7U05BUFNIT1RfRElSfSIKZWNobyAiU05BUFNIT1RfREFZUz0ke1NOQVBTSE9UX0RBWVN9IgplY2hvICItLS0tLS0tLS0tLS0tLS0iCgpzaG9wdCAtcyBub2Nhc2VtYXRjaAppZiBbWyAiJHtUSElTX0hPU1R9IiAhPSAke1NOQVBTSE9UX0hPU1R9KiBdXTsgdGhlbgogICAgZWNobyAiVGhpcyBub2RlICgke1RISVNfSE9TVH0pIGlzIG5vdCB0aGUgZXRjZC1zbmFwc2hvdCB0YXJnZXQgbm9kZSAoJHtTTkFQU0hPVF9IT1NUfSkuIiAKICAgIGV4aXQgMApmaQoKdmFsaWQ9MApmb3IgaCBpbiAke1ZBTElEX0RJUlN9OyBkbwogICAgaWYgIFtbICIke1NOQVBTSE9UX0RJUn0iID1+IF4ke2h9L1thLXpBLXowLTlfXSsuKiBdXTsgdGhlbgogICAgICAgIHZhbGlkPTEKICAgICAgICBicmVhawogICAgZmkKZG9uZQppZiBbWyAiJHt2YWxpZH0iID09ICIwIiAgXV07IHRoZW4KICAgIGVjaG8gIiR7U05BUFNIT1RfRElSfSBpcyBub3QgYSB2YWxpZCB0YXJnZXQgZGlyZWN0b3J5LiIKICAgIGV4aXQgMQpmaQoKbWtkaXIgLXAgJHtTTkFQU0hPVF9ESVJ9CgovdXNyL2xvY2FsL2Jpbi9jbHVzdGVyLWJhY2t1cC5zaCAke1NOQVBTSE9UX0RJUn0KCnNsZWVwIDMKCmVjaG8gIi0tLSBQcmUtcHVyZ2Ugc3RhdGUgLS0tIgpscyAtbHRhICR7U05BUFNIT1RfRElSfQoKZWNobyAiLS0tIFB1cmdpbmcgc3RhbGUgc25hcHNob3RzIC0tLSIKZmluZCAke1NOQVBTSE9UX0RJUn0gLXR5cGUgZiAtbXRpbWUgKyR7U05BUFNIT1RfREFZU30gLXByaW50IC1kZWxldGUK
        mode: 493
        overwrite: true
    systemd:
      units:
        - name: etcd-snapshot.service
          contents: |
            [Unit]
            Description=Scheduled snapshot of etcd datastore & k8s resources
            
            [Service]
            Type=oneshot
            Environment=HOST=master-0.ocpa
            Environment=TGT_DIR=/home/core/etcd-snapshots
            Environment=DAYS=3
            ExecStart=/bin/bash /usr/local/bin/etcd-snapshot.sh ${HOST} ${TGT_DIR} ${DAYS}
          enabled: false
        - name: etcd-snapshot.timer
          contents: |
            [Unit]
            Description=Run etcd-snapshot.service daily
            
            [Timer]
            OnCalendar=00:01:00 America/New_York
          enabled: true
...