apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 000-helloworld
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=The Ultimate Heatmiser Test
            Before=kubelet.service

            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=-mkdir -p /tmp/heatmiser

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: heatmiser.service
