---
apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-snapshotter
spec:
  template:
    spec:
      containers:
      - name: root
        image: staranto/etcd-snapshot-archiver:0.1.0
        imagePullPolicy: Always
        command: ["/usr/local/bin/cluster-backup.sh", "/tmp/from-root-pod"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/"
          name: hostpath-snapshot
        - mountPath: "/tmp/etcd-snapshots-archive"
          name: snapshot-archive
      volumes:
      - name: hostpath-snapshot
        persistentVolumeClaim:
          claimName: pvc-node-root
      - name: snapshot-archive
        persistentVolumeClaim:
          claimName: b-pvc
      restartPolicy: Never
      terminationGracePeriodSeconds: 1
      nodeSelector:
        kubernetes.io/hostname: master-2
...
