---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    machineconfiguration.openshift.io/mco-built-in: ''
    operator.machineconfiguration.openshift.io/required-for-upgrade: ''
  name: master-etcd-snapshot-pool
spec:
  machineConfigSelector:
    matchLabels:
      machineconfiguration.openshift.io/role: etcd-snapshot
  nodeSelector:
    matchLabels:
      taranto.dev/etcd-snapshot: ''
  paused: false
...
