---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-etcd-snapshots
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/etcd-snapshots"
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-etcd-snapshots
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
...

